import org.jetbrains.gradle.ext.settings
import org.jetbrains.gradle.ext.taskTriggers

plugins {
    id("java-library")
    id("maven-publish")
    id("idea")
    id("net.neoforged.moddev") version "2.0.141"
}

// Accessing properties from gradle.properties
val parchment_mappings_version = "2025.12.21-nightly-SNAPSHOT"
val parchment_minecraft_version = "1.21.11"

version = project.property("mod.version") as String
group =  project.property("mod.group") as String

repositories {
    mavenLocal()
    mavenCentral()
}

base {
    archivesName.set(project.property("mod.id") as String )
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

neoForge {
    // version.set(neo_version)  // So... I have to directly override it instead of doing that.
    version = "26.1.0.19-beta"


    parchment {
        mappingsVersion.set(parchment_mappings_version)
        minecraftVersion.set(parchment_minecraft_version)
    }

    // Default run configurations.
    runs {
        configureEach {
            // Recommended logging data for a userdev environment
            systemProperty("forge.logging.markers", "REGISTRIES")
            logLevel.set(org.slf4j.event.Level.DEBUG)
        }

        create("client") {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", project.property("mod.id") as String)
        }

        create("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", project.property("mod.id") as String)
        }

        create("gameTestServer") {
            type.set("gameTestServer")
            systemProperty("neoforge.enabledGameTestNamespaces", project.property("mod.id") as String)
        }

        create("data") {
            clientData()
            programArguments.addAll(
                "--mod", project.property("mod.id") as String,
                "--all",
                "--output", file("src/generated/resources/").absolutePath,
                "--existing", file("src/main/resources/").absolutePath
            )
        }
    }

    mods {
        create(project.property("mod.id") as String) {
            sourceSet(sourceSets.main.get())
        }
    }
}

// Include resources generated by data generators.
sourceSets.main {
    resources {
        srcDir("src/generated/resources")
    }
}

dependencies {
    // Add dependencies here
}

// Expanding replace properties in resource targets.
val generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
    val replaceProperties = mapOf(
        "minecraft_version"      to project.findProperty("minecraft_version"),
        "minecraft_version_range" to project.findProperty("minecraft_version_range"),
        "neo_version"            to project.findProperty("neo_version"),
        "neo_version_range"      to project.findProperty("neo_version_range"),
        "loader_version_range"   to project.findProperty("loader_version_range"),
        "mod_id"                 to project.property("mod.id") as String,
        "mod_name"               to project.findProperty("mod_name"),
        "mod_license"            to project.findProperty("mod_license"),
        "mod_version"            to project.property("mod.version") as String,
        "mod_authors"            to project.findProperty("mod_authors"),
        "mod_description"        to project.findProperty("mod_description")
    )
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from("src/main/resources/neoforge.mods.toml")
    into("build/generated/sources/modMetadata")
}

// Include the output of "generateModMetadata"
sourceSets.main {
    resources {
        srcDir(generateModMetadata)
    }
}

// To avoid having to run "generateModMetadata" manually
neoForge.ideSyncTask(generateModMetadata)

publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri(layout.projectDirectory.dir("repo"))
        }
    }
}

idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}
